name: Echo
on:
  pull_request:
    branches: ["main"]

env:
    STEP_NAME: Hello world

jobs:
  echo:
    name: Echo
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: ${{ env.STEP_NAME }}
        run: echo ${{ secrets.SOME_SECRET }}